import { ModelStatsRunner } from "./ModelStatsRunner";
import { ModelStatsExportUtils, ModelStatsRecord } from "./modelStatsExportUtils";
import {
  graph,
  trash,
  socialMedia,
  courses,
  lts,
  productionLineV1,
  productionLineV2,
  productionLineV3,
  coursesV1,
  coursesV2,
  classroom,
  classroomRL,
  classroomFol,
  cv,
  array,
  binaryTree,
  classDiagram,
  cTree,
  dll,
  singlyLinkedList,
  fsm,
  handshake,
  trashLtl,
  bempl,
  farmer,
  grade,
  nQueens,
  git,
  trainStationFol,
  trainStationLTL,
  trashFol,
  trashRL,
  frankervrep,
  checkmate,
  chord,
  diffAndCD2,
  smartHome,
  sdwSimplified,
  projetoLogica,
  gatewayTCB,
  statecoverage,
  drone,
  icd,
  theatre,
  javaMetaModel,
  randomSkiJumping,
  modeloAlloy,
  onlineShop,
} from "./models-runners";

const records: ModelStatsRecord[] = [];
const exporter = new ModelStatsExportUtils();

const modelStatsRunners = [
  graph,
  trash,
  socialMedia,
  courses,
  lts,
  productionLineV1,
  productionLineV2,
  productionLineV3,
  coursesV1,
  coursesV2,
  classroom,
  classroomRL,
  classroomFol,
  cv,
  array,
  binaryTree,
  classDiagram,
  cTree,
  dll,
  singlyLinkedList,
  fsm,
  handshake,
  trashLtl,
  bempl,
  farmer,
  grade,
  nQueens,
  git,
  trainStationFol,
  trainStationLTL,
  trashFol,
  trashRL,
  frankervrep,
  checkmate,
  chord,
  diffAndCD2,
  smartHome,
  sdwSimplified,
  projetoLogica,
  gatewayTCB,
  statecoverage,
  drone,
  icd,
  theatre,
  javaMetaModel,
  randomSkiJumping,
  modeloAlloy,
  onlineShop,
].map(
  (model) => new ModelStatsRunner(model.name, model.getCompleteFileUri())
);

for (const runner of modelStatsRunners) {
  runner.runModelStatsTests((record) => records.push(record));
}

after(() => {
  exporter.writeCsv(records);
});
